### ISSUE TITLE
Close ports for the conjur follower

### ISSUE THREAD

**Issue by h-artzi** [cyberark/kubernetes-conjur-deploy#171]
In the [conjur-follower.yml](https://github.com/cyberark/kubernetes-conjur-deploy/blob/master/openshift/conjur-follower.yaml) update the exposed ports:

In the [service](https://github.com/cyberark/kubernetes-conjur-deploy/blob/8a4ea1e0be668ed63aeb501cde87de2194bfcc6d/openshift/conjur-follower.yaml#L3):
Do not expose port 636.
Proposed:
```
apiVersion: v1
kind: Service
metadata:
  name: conjur-follower
  labels:
    app: conjur-follower
spec:
  ports:
  - port: 443
    name: https
  selector:
    app: conjur-follower
 ```

For the [conjur-appliance container](https://github.com/cyberark/kubernetes-conjur-deploy/blob/8a4ea1e0be668ed63aeb501cde87de2194bfcc6d/openshift/conjur-follower.yaml#L98), we shouldn't expose port 636 or 5433
Proposed:
```
ports:
  - containerPort: 443
    name: https
  - containerPort: 5432
    name: pg-main
```
