### ISSUE TITLE
Sample manifests include readiness probes

### ISSUE THREAD

**Issue by jvanderhoof** [cyberark/kubernetes-conjur-deploy#41]
Our application manifests for Kubernetes and OpenShift do not include Probes to determine if the follower is healthy, and thus available to receive requests.  For an operator, it's critical that followers are healthy to avoid traffic being routed to followers which cannot service requests.

GIVEN a Kubernetes or OpenShift cluster
WHEN I configure a follower using the script
AND I scale followers up by one (bringing up an un-configured follower)
THEN request traffic is not routed to the unhealthy follower

**Dev Notes**
Health checks in K8s/OC can be configured using Readiness Probes. Probes are part of the Pod spec.  Adding a probe to a deployment should look something  like:

```yml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: conjur-follower
spec:
  replicas: {{ CONJUR_FOLLOWER_COUNT }}
  template:
    metadata:
      labels:
        app: conjur-follower
        name: conjur-follower
        role: follower
    spec:
      serviceAccountName: conjur-cluster
      containers:
      - name: conjur-appliance
        image: {{ CONJUR_APPLIANCE_IMAGE }}
        imagePullPolicy: {{ IMAGE_PULL_POLICY }}
        env:
          - name: CONJUR_AUTHENTICATORS
            value: authn-k8s/{{ AUTHENTICATOR_ID }}
        ports:
        - containerPort: 443
          name: https
        - containerPort: 636
          name: ldaps
        - containerPort: 5432
          name: pg-main
        - containerPort: 5433
          name: pg-audit
        readinessProbe:
          httpGet:
            path: /health
            port: 443
          initialDelaySeconds: 15
          timeoutSeconds: 1
      imagePullSecrets:
        - name: dockerpullsecret
```
Note the `readinessProbe` pointing to the `health` endpoint.
